{{- if .Values.ssl.useCertManager }}
{{- if (.Capabilities.APIVersions.Has "cert-manager.io/v1") }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: certmanager.k8s.io/v1alpha1
{{- end }}
kind: Certificate
metadata:
  name: {{ template "traefik.fullname" . }}
  labels:
      app: {{ template "traefik.name" . }}
      chart: {{ template "traefik.chart" . }}
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
    # We have to add the following annotation so that the upgrade does
    # not fail with "already exists" error. See more details in:
    # https://github.com/helm/helm/issues/5482
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  {{- if .Values.initCertJobImage }}
  secretName: {{ template "traefik.fullname" . }}-certificate-temporary
  {{- else }}
  # if we do not have a initCertJobImage set, we directly write the certificate
  secretName: {{ template "traefik.fullname" . }}-certificate
  {{- end }}
  issuerRef:
  {{- if .Values.certIssuerRef }}
    {{- toYaml .Values.certIssuerRef | nindent 4 }}
  {{- else }}
    name: kubernetes-ca
    kind: ClusterIssuer
  {{- end }}
  dnsNames:
    - {{ .Values.ssl.defaultCN }}
    {{- range .Values.ssl.defaultSANList }}
    - {{ . }}
    {{- end }}
  duration: {{ .Values.ssl.defaultDuration }}
  {{- if .Values.ssl.defaultUsages }}
  usages:
    {{- toYaml .Values.ssl.defaultUsages | nindent 2 }}
  {{- end }}
{{- if (.Capabilities.APIVersions.Has "cert-manager.io/v1") }}
  subject:
  {{- toYaml .Values.ssl.defaultSubject | nindent 2 }}
{{- else }}
  organization:
  {{- toYaml .Values.ssl.defaultSubject.organizations | nindent 2 }}
{{- end }}
  # The commonName will get replaced by kubeaddons-config
  # init-container for traefik
  commonName: {{ .Values.ssl.defaultCN }}
{{- end }}
